import { Ranga, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const ranga = Ranga({
  variable: "--font-ranga-bold",
  subsets: ["latin"],
  weight: "700",
});

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto_condensed",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ranga.variable} ${robotoCondensed.variable} ${ranga.className} ${robotoCondensed.className}`}>
      <body
        className={`font-roboto antialiased flex justify-center items-center min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
