import { Ranga, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { GRID_DATA_ITEMS } from "./data";
import Link from "next/link";

const ranga = Ranga({
  variable: "--font-ranga-bold",
  subsets: ["latin"],
  weight: '700'
});

const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto_condensed',
  subsets: ["latin"],
  weight: '400'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ranga.variable} ${robotoCondensed.variable}`}>
      <body
        className={`font-roboto antialiased flex justify-center items-center min-h-screen`}
      >
        <div className="w-[350px] lg:w-[1000px] flex flex-col items-center pt-4 pb-4">
          <div className="w-full bg-slate-100 flex flex-col items-center pb-10 pt-10">
            <div className="title">
              DAVID KANDO MUSIC
            </div>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-1">
              {GRID_DATA_ITEMS.map((gridDataItem) => {
                const { id, attributes } = gridDataItem;

                return (
                  <Link key={id} href={attributes.href}>
                    <div
                      className={`${attributes.background} w-36 h-36 lg:w-52 lg:h-52 flex items-end border-black border-[2px]`}
                    >
                      <div
                        className={` font-ranga bg-slate-200/75 w-full text-center mb-2 text-sm lg:text-lg h-[18px] lg:h-[30px] hover:text-white hover:bg-slate-700/75`}
                      >
                        {attributes.text}
                      </div>
                    </div>
                  </Link>
                );
              })}
            </div>
          </div>
          <br />
          {children}
        </div>
      </body>
    </html>
  );
}
