import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GRID_DATA_ITEMS } from "./data";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          {GRID_DATA_ITEMS.map((gridDataItem) => {
            const { id, attributes } = gridDataItem;

            return(
              <div key={id}> 
              <Link href={attributes.href}>{attributes.text}</Link>
              </div>
            )
          })}
        </div>
        <br />
        {children}
      </body>
    </html>
  );
}
